#!/usr/bin/python

import errno
import os
import sys
from datetime import datetime

# All log entries will be stored in .logit in user home
logit_location = os.path.expanduser('~/.logit')

# Create the .logit directory if it doesn't exist.
try:
    os.makedirs(logit_location)
except OSError as exception:
    if exception.errno != errno.EEXIST:
        raise

# Write one log file per day, opening and appending to throughout the day.
now = datetime.now()
file_name = os.path.join(logit_location, "logit-%s.log" % (now.strftime('%m-%d-%Y')))
with open(file_name, 'a+') as f:
    f.write("".join(("%s: " % now.strftime('%H:%M:%S'), " ".join(sys.argv[1:]), '\n')))
